#!/bin/bash

set -o errexit
set -o nounset
set -o xtrace
 
readonly TARGET_HOST=pi@raspberrypi.local
readonly TARGET_PATH=/home/pi/actix_hello_world
readonly TARGET_ARCH=armv7-unknown-linux-gnueabihf
readonly SOURCE_PATH=./target/${TARGET_ARCH}/release/actix_hello_world

cargo build --release --target=${TARGET_ARCH}
rsync ${SOURCE_PATH} ${TARGET_HOST}:${TARGET_PATH}
ssh -t ${TARGET_HOST} ${TARGET_PATH}
