[package]
name = "assignment_4"
version = "0.1.0"
authors = ["Muhammad Sameem <sameemgujjar123@yahoo.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "2.0.0"
actix-rt = "1.0.0"